# coding:utf-8

# log level
LOG_CRITICAL = 1
LOG_ERROR = 2
LOG_WARNING = 3
LOG_INFO = 4
LOG_DEBUG = 5


# login error code 1x 1:登录 x:code
LOGIN_SUCC = 10
LOGIN_USERNAME_ERROR = 11
LOGIN_PASSWORD_ERROR = 12
LOGIN_TOO_FAST = 13
LOGIN_UNKNOWN_ERROR = 14
LOGIN_PAGE_ERROR = 15
LOGIN_CODE_ERROR = 16
LOGIN_CODE_INPUT_ERROR = 17
LOGIN_OPEN_FAIL = 18
LOGIN_CODE_SAVE_ERROR = 19

# get info error code 2xx 2:获取信息 x:教务处-学工网 x:code
GET_JWC_PAGE_ERROR = 211
GET_JWC_INFO_ERROR = 212
GET_JWC_NO_INFO_ERROR = 213

# info value
INFO_LOACTION_HKG = 1
INFO_LOACTION_LQ = 2
INFO_SEX_MAN = 1
INFO_SEX_WOMAN = 2
INFO_IN_SCHOOL = 1
INFO_NOT_IN_SCHOOL = 2

# site type
SITE_TYPE_JWC = 1
SITE_TYPE_XGW = 2

# captcha type
CAPTCHA_NUMBER = 1
CAPTCHA_CHARACTER = 2
CAPTCHA_MIX = 3

# captcha identify result code
IDENTIFY_RIGHT = 0
IDENTIFY_WRONG = 1
IDENTIFY_SUCC = 2
IDENTIFY_FAIL = 3
IDENTIFY_EXCEPTION = 4

# selenium driver type
DRIVER_TYPE_CHROME = 1
DRIVER_TYPE_FIREFOX = 2
DRIVER_TYPE_PHANTOMJS = 3






