# coding:utf-8

# log level
LOG_CRITICAL = 1
LOG_ERROR = 2
LOG_WARNING = 3
LOG_INFO = 4
LOG_DEBUG = 5


# login error code 1x 1:登录 x:code
LOGIN_SUCC = 10
LOGIN_USERNAME_ERROR = 11
LOGIN_PASSWORD_ERROR = 12
LOGIN_TOO_FAST = 13
LOGIN_UNKNOWN_ERROR = 14
LOGIN_PAGE_ERROR = 15
LOGIN_CODE_ERROR = 16
LOGIN_CODE_INPUT_ERROR = 17
LOGIN_OPEN_FAIL = 18
